version: '2'
services:
  spring:
    container_name: tictactoe
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tictactoe
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres:
    image: 'postgres:14.2-alpine'
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=tictactoe
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
